widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: false
  -
    name: 'SURI_TEXT'
    description: 'Widget text'
    type: TEXT
    usageExample: 'My content'
    required: false
  -
    name: 'SURI_TITLE_SIZE'
    description: 'Title size'
    type: COMBO
    defaultValue: 'small'
    possibleValuesMap:
      -
        jsKey: small
        value: Small
      -
        jsKey: medium
        value: Medium
      -
        jsKey: large
        value: Large
      -
        jsKey: very-large
        value: Very large
    required: true
  -
    name: 'SURI_TEXT_SIZE'
    description: 'Text size'
    type: COMBO
    defaultValue: 'small'
    possibleValuesMap:
      -
        jsKey: small
        value: Small
      -
        jsKey: medium
        value: Medium
      -
        jsKey: large
        value: Large
      -
        jsKey: very-large
        value: Very large
    required: true