widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget Title'
    type: STRING
    usageExample: 'My new Dashboard'
    required: true
  -
    name: 'SURI_TEXT'
    description: 'Widget text'
    type: STRING
    usageExample: 'My content'
    required: true