widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    defaultValue: 'Timeline'
    required: true
  -
    name: 'SURI_PROJECT'
    description: 'Jira project name'
    type: TEXT
    required: true
