widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_PROJECT'
    description: 'Jira project name'
    type: TEXT
    usageExample: 'My Jira project'
    required: true
  -
    name: 'SURI_VERSION'
    description: 'Jira project version'
    type: TEXT
    usageExample: '1.2'
    required: true
  -
    name: 'SURI_REGEX'
    description: 'Filter by regular expression'
    type: TEXT
    usageExample: 'UnitTest.*'
    required: false
  -
    name: 'SURI_DISPLAY_PERCENT_EXEC'
    description: 'Display the percentage of execution on the progress bar'
    type: COMBO
    defaultValue: 'YES'
    possibleValuesMap:
      -
        jsKey: 'YES'
        value: 'Yes'
      -
        jsKey: 'NO'
        value: 'No'
    required: true
