widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: SURI_PROJECT
    description: 'Project ID'
    type: TEXT
    usageExample: '1234'
    required: true
  -
    name: SURI_TYPE_GRAPH
    description: 'Graphic type'
    type: COMBO
    defaultValue: 'pie'
    possibleValuesMap:
      -
        jsKey: pie
        value: Pie
      -
        jsKey: horizontalBar
        value: Horizontal Bar
      -
        jsKey: bar
        value: Bar
    required: true