widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_LIMIT'
    description: 'Maximum time in queue (in minutes)'
    type: NUMBER
    usageExample: 60
    required: true
  -
    name: 'SURI_CRITICAL_LIMIT'
    description: 'Maximum number of jobs in the queue to trigger an alarm'
    type: NUMBER
    usageExample: 10
    required: true
