widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: STRING
    defaultValue: 'Jenkins waiting queue'
    required: true
  -
    name: 'SURI_LIMIT'
    description: 'Max time in queue (in minutes)'
    type: INTEGER
    required: true
  -
    name: 'SURI_CRITICAL_LIMIT'
    description: 'MAX authorized number of jobs in queue'
    type: INTEGER
    required: true