widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    defaultValue: 'Burndown'
    required: true
  -
    name: 'SURI_JQL'
    description: 'Jira JQl Query'
    type: TEXT
    usageExample: 'fixVersion = "XXX 1.1"'
    required: true
