widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_JQL'
    description: 'Jira JQL query to retrieve the sprint issues'
    type: TEXT
    usageExample: 'Sprint = "Sprint Name"'
    usageTooltip: 'The number of retrieved issues is currently limited to 1000'
    required: true
