widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    defaultValue: 'Active User'
    required: false
  -
    name: 'SURI_DELAI'
    description: 'Span time to compare widget data in hours'
    type: NUMBER
    defaultValue: '24'
    required: true
  -
    name: 'SURI_DATE'
    description: 'Beginning of the wanted period (format : DDMMYYYY)'
    type: TEXT
    usageExample: '31122017'
    required: true
  -
    name: 'SURI_USER'
    description: 'Filter on User id (Start with)'
    type: TEXT
    required: false
