widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    defaultValue: 'Slave Status'
    required: true
  -
    name: 'SURI_REGEX'
    description: 'Slave Regex'
    type: TEXT
    usageExample: 'SLAVE_.*'
    required: false
