widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_JQL'
    description: 'Jira JQL query'
    type: TEXT
    usageExample: 'project=XXX and (component=jenkins or component=XXX)'
    required: true
  -
    name: 'SURI_DISPLAY_LEGEND'
    description: 'Display the legend of the chart'
    type: BOOLEAN
    required: false
