widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: STRING
    defaultValue: 'Release X.X'
    required: true
  -
    name: 'SURI_JQL_ALL'
    description: 'Jira JQL query to count all issue'
    type: STRING
    usageExample: 'fixVersion = "XXX 1.1" AND project = XXXX'
    required: true
  -
    name: 'SURI_JQL_CLOSED'
    description: 'Jira JQL query to count all closed issue'
    type: STRING
    usageExample: 'fixVersion = "XXX 1.1" AND project = XXXX and status in (3_Closed, Done, "Done Done")'
    required: true
  -
    name: 'SURI_DISPLAY_COUNT'
    description: 'Display count of data on the widget'
    type: BOOLEAN
    required: false