widgetParams:
  -
    name: 'SURI_JIRA_PROJECT'
    description: 'Jira Project Key'
    type: TEXT
    usageExample: 'OSYS'
    required: true
  -
    name: 'SURI_JIRA_START_RANGE'
    description: 'Start range from now (in days), to include jira issues created within it'
    type: NUMBER
    defaultValue: '30'
    usageTooltip: 'If you choose 30, all issues created from 30 days until now will be selected'
    required: true
  -
    name: 'SURI_JIRA_VALUE_FORMAT'
    description: 'Choose Lead Time value format'
    type: COMBO
    defaultValue: 'DAYS'
    required: true
    possibleValuesMap:
      -
        jsKey: 'DAYS'
        value: Days
      -
        jsKey: 'HOURS'
        value: Hours
      -
        jsKey: 'MINUTES'
        value: Minutes
      -
        jsKey: 'SECONDS'
        value: Seconds
  -
    name: 'WIDGET_CONFIG_JIRA_INITIAL_STATUS'
    description: 'Name of a jira issue status where the calculation of lead time must start'
    type: TEXT
    usageExample: 'Started'
    usageTooltip: "By default, the lead time is based on time delta between creation date and resolution date of the jira issue. You can specify the name of a jira issue status if you need the lead time between the date of the specific jira issue status and the resolution date. Remark, if the status doesn't exist in the history of a jira issue, the creation date will be used"
    required: false