widgetParams:
  -
    name: SURI_PROJECT
    description: 'Project ID'
    type: TEXT
    usageExample: '1234'
    required: true
  -
    name: SURI_PROJECT_BRANCH
    description: 'Filter on a branch'
    type: TEXT
    usageExample: 'dev'
    required: false
