widgetParams:
  -
    name: 'SURI_PDF'
    description: 'Select your PDF'
    type: FILE
    acceptFileRegex: '^data:application\/pdf;base64,.+$'
    required: true
  -
    name: 'SURI_DELAI'
    description: 'Delay between slides (in milliseconds)'
    type: NUMBER
    usageExample: '5000'
    required: true
