widgetParams:
  -
    name: 'SURI_PDF'
    description: 'Choose your PDF'
    type: FILE
    acceptFileRegex: '/(\.|\/)(pdf)$/'
    required: true
  -
    name: 'SURI_DELAI'
    description: 'Delay between two slides (in milliseconds)'
    type: INTEGER
    defaultValue: '5000'
    required: true