widgetParams:
  -
    name: 'SURI_DELAI'
    description: 'Span time to compare widget data in hours'
    type: NUMBER
    defaultValue: '24'
    required: true
  -
    name: 'GITHUB_ORG'
    description: 'Filter for a given organization'
    type: TEXT
    required: true
  -
      name: 'GITHUB_PROJECT'
      description: 'Filter for a given project'
      type: TEXT
      required: true
