widgetParams:
  -
    name: 'SURI_JOB'
    description: 'Job name'
    type: TEXT
    usageExample: '200-DeploySpringBoot-monitor_back'
    required: true
  -
    name: 'SURI_DISPLAY_MODE'
    description: 'Display mode when project has been rebuilt'
    type: COMBO
    defaultValue: 'upstream'
    possibleValuesMap:
      -
        jsKey: 'upstream'
        value: 'Upstream'
      -
        jsKey: 'user'
        value: 'User'
    required: false
