widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_REGEX'
    description: 'Slave regex'
    type: TEXT
    usageExample: 'SLAVE_.*'
    required: false
