widgetParams:
  -
    name: 'SURI_DELAI'
    description: 'Span time to compare widget data in hours'
    type: NUMBER
    defaultValue: '24'
    required: true
  -
    name: 'SURI_REGEXP'
    description: 'Filter regex on User ID (case-insensitive matching)'
    type: TEXT
    required: false
