widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_JQL'
    description: 'Jira JQL query'
    type: TEXT
    usageExample: 'project = XXXX and assignee is EMPTY and status not in (Closed, Completed, Done, "Done Done") ORDER BY createdDate DESC'
    required: true
  -
    name: 'SURI_DELAI'
    description: 'Span time to compare widget data in hours'
    type: NUMBER
    defaultValue: '24'
    required: true
