widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_DATE'
    description: 'Start date to count users'
    type: TEXT
    usageExample: '31122017'
    usageTooltip: 'Format required: DDMMYYYY'
    required: false
  -
    name: 'SURI_SEARCH_BY_IDENTIFIER'
    description: 'Filter users by identifier. Substring accepted'
    type: TEXT
    usageExample: 'jack_smith'
    required: false
