widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_DATE'
    description: 'Start date to count users (DDMMYYYY)'
    type: TEXT
    usageExample: '31122017'
    required: false
  -
    name: 'SURI_SEARCH_BY_IDENTIFIER'
    description: 'Filter users by identifier'
    type: TEXT
    usageExample: 'jack_smith'
    required: false
