widgetParams:
  - 
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_RUNNER_TAGS'
    description: 'Filter runners by tags, separated by a comma'
    type: TEXT
    usageExample: 'tag1,tag2'
    required: false
