widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: STRING
    usageExample: 'Number of job'
    required: false
  -
    name: 'SURI_PERIOD'
    description: '"Period type" to retrieve data (YEAR,MONTH,WEEK,DAY)'
    type: COMBO
    possibleValuesMap:
      -
        jsKey: 'YEAR'
        value: 'YEAR'
      -
        jsKey: 'MONTH'
        value: 'MONTH'
      -
        jsKey: 'WEEK'
        value: 'WEEK'
      -
        jsKey: 'DAY'
        value: 'DAY'
    required: true
  -
    name: 'SURI_NB_PERIOD'
    description: 'Number of "period type"'
    type: NUMBER
    defaultValue: '1'
    required: true
  -
    name: 'SURI_VIEW'
    description: 'View or sub view url'
    type: STRING
    usageExample: 'https://jenkins.com/jenkins/view/SC/view/PCR/ or view/SC'
    required: false
  -
    name: 'SURI_JOB_TYPE'
    description: 'Job type to filter (All, Generic)'
    type: COMBO
    possibleValuesMap:
      -
        jsKey: 'All'
        value: 'All'
      -
        jsKey: 'GEN'
        value: 'Generic'
    required: true
