widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_WEEK'
    description: 'Period of activity (in weeks)'
    type: NUMBER
    defaultValue: '12'
    required: true
  -
    name: 'SURI_ORDERBY'
    description: 'Order extension by'
    type: COMBO
    defaultValue: 'ISSUES'
    possibleValuesMap:
      -
        jsKey: 'ISSUES'
        value: 'Issues'
      -
        jsKey: 'TIMETOCLOSE'
        value: 'Average time to close issues'
      -
        jsKey: 'DAYOFISSUES'
        value: 'Day of issues'
    required: true
  -
    name: 'SURI_TYPE_GRAPH'
    description: 'Graph type'
    type: COMBO
    defaultValue: 'horizontalBar'
    possibleValuesMap:
      -
        jsKey: 'pie'
        value: 'Pie'
      -
        jsKey: 'horizontalBar'
        value: 'Horizontal bar'
      -
        jsKey: 'bar'
        value: 'Vertical bar'
    required: true
