widgetParams:
  -
    name: 'SURI_DELAI'
    description: 'Span time to compare widget data in hours'
    type: INTEGER
    defaultValue: '24'
    required: true
  -
    name: 'GITLAB_PROJECT'
    description: 'Filter for a given project'
    type: STRING
    required: true
  -
      name: 'GITLAB_BRANCH'
      description: 'Filter for a given branch'
      type: STRING
      required: true