widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_PERIOD'
    description: 'Time period used to filter the jobs by last execution date'
    type: COMBO
    defaultValue: 'Month'
    possibleValuesMap:
      -
        jsKey: 'Year'
        value: 'Year'
      -
        jsKey: 'Month'
        value: 'Month'
      -
        jsKey: 'Week'
        value: 'Week'
      -
        jsKey: 'Day'
        value: 'Day'
    required: true
  -
    name: 'SURI_NB_PERIOD'
    description: 'Unit of the selected period'
    type: 'NUMBER'
    defaultValue: 1
    required: true
  -
    name: 'SURI_VIEW'
    description: 'View or sub view URL'
    type: TEXT
    usageExample: 'https://jenkins.com/jenkins/view/SC/view/PCR/ or view/SC'
    required: false
  -
    name: 'SURI_JOB_SCM_TYPE'
    description: 'SCM type to display'
    type: COMBO
    defaultValue: 'All'
    possibleValuesMap:
      -
        jsKey: 'All'
        value: 'All'
      -
        jsKey: 'Git'
        value: 'Git'
      -
        jsKey: 'SVN'
        value: 'SVN'
    required: true
  -
    name: 'SURI_JOB_TYPE'
    description: 'Job type to filter'
    type: COMBO
    defaultValue: 'All'
    possibleValuesMap:
      -
        jsKey: 'All'
        value: 'All'
      -
        jsKey: 'Generic'
        value: 'Generic'
    required: true
